name: Connect to Ollama via Tailscale

on:
  push:
    branches: [main, test-cicd]
    paths:
      - 'backend/**'
      - '.github/workflows/ollama-ci.yml'
  workflow_dispatch:

jobs:
  call-ollama:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: 1.66.4  # or latest stable

      - name: Confirm Tailscale Connection
        run: tailscale status

      - name: Wait for Tailscale connection
        run: sleep 5

      - name: Test connection to Ollama
        run: |
          echo "Pinging Ollama server..."
          curl --fail http://100.100.108.13:11434/api/tags || (echo "❌ Failed to connect to Ollama"; exit 1)
